default: &default
  adapter: postgresql
  encoding: unicode
  username: default
  password: mhZ3XIUw1JFB
  host: ep-broad-paper-a4vu1c34-pooler.us-east-1.aws.neon.tech

development:
  <<: *default
  database: verceldb

test:
  <<: *default
  database: verceldb

production:
  <<: *default
  database: verceldb
  username: default
  password: mhZ3XIUw1JFB